In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('Data.csv')
x = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [3]:
print(x)

[['Japan' 45.0 70000.0]
 ['Indonesia' 25.0 45000.0]
 ['Vietnam' 30.0 50000.0]
 ['Indonesia' 35.0 61000.0]
 ['Japan' 40.0 nan]
 ['Vietnam' 38.0 56000.0]
 ['Indonesia' nan 54000.0]]


In [4]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No']


In [5]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:,1:3])
x[:, 1:3] =imputer.transform(x[:,1:3])

In [6]:
print(x)

[['Japan' 45.0 70000.0]
 ['Indonesia' 25.0 45000.0]
 ['Vietnam' 30.0 50000.0]
 ['Indonesia' 35.0 61000.0]
 ['Japan' 40.0 56000.0]
 ['Vietnam' 38.0 56000.0]
 ['Indonesia' 35.5 54000.0]]


In [7]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [8]:
print(x)

[[0.0 1.0 0.0 45.0 70000.0]
 [1.0 0.0 0.0 25.0 45000.0]
 [0.0 0.0 1.0 30.0 50000.0]
 [1.0 0.0 0.0 35.0 61000.0]
 [0.0 1.0 0.0 40.0 56000.0]
 [0.0 0.0 1.0 38.0 56000.0]
 [1.0 0.0 0.0 35.5 54000.0]]


In [9]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [10]:
print(y)

[0 1 0 0 1 1 0]


In [11]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=1)

In [12]:
print(x_train)

[[1.0 0.0 0.0 25.0 45000.0]
 [0.0 1.0 0.0 45.0 70000.0]
 [0.0 1.0 0.0 40.0 56000.0]
 [1.0 0.0 0.0 35.0 61000.0]
 [0.0 0.0 1.0 38.0 56000.0]]


In [13]:
print(x_test)

[[1.0 0.0 0.0 35.5 54000.0]
 [0.0 0.0 1.0 30.0 50000.0]]


In [14]:
print(y_train)

[1 0 1 0 1]


In [15]:
print(y_test)

[0 0]


In [16]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:,3:] = sc.fit_transform(x_train[:,3:])
x_test[:,3:] = sc.transform(x_test[:,3:])

In [17]:
print(x_train)

[[1.0 0.0 0.0 -1.7440158600403648 -1.5528361541085662]
 [0.0 1.0 0.0 1.2629080365809535 1.5281879611862081]
 [0.0 1.0 0.0 0.5111770624256239 -0.19718554337886557]
 [1.0 0.0 0.0 -0.24055391172970567 0.4190192796800893]
 [0.0 0.0 1.0 0.21048467276349206 -0.19718554337886557]]


In [18]:
print(x_test)

[[1.0 0.0 0.0 -0.1653808143141727 -0.4436674726024475]
 [0.0 0.0 1.0 -0.9922848858850352 -0.9366313310496114]]
